OnceUpoonABook/Models/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using OnceUpoonABook.Data.Base;
using OnceUpoonABook.Data.Enums;
using OnceUpoonABook.Data.ViewModels;

namespace OnceUpoonABook.Models
{
    public class Book: IEntityBase
    {
        public Book()
        {

        }
        public Book(AddBookViewModel addBookViewModel)
        {
            Title = addBookViewModel.Title;
            Description = addBookViewModel.Description;
            CoverURL = addBookViewModel.CoverURL;
            PublicationYear = addBookViewModel.PublicationYear;
            Pages = addBookViewModel.Pages;
            Price = addBookViewModel.Price;
            BookCategory = addBookViewModel.BookCategory;
            Language = addBookViewModel.Language;
            PublisherId = addBookViewModel.PublisherId;

        }

        public Book(EditBookViewModel bookViewModel)
        {
            Id = bookViewModel.Book.Id;
            Description = bookViewModel.Book.Description;
            Title = bookViewModel.Book.Title;
            CoverURL = bookViewModel.Book.CoverURL;
            PublicationYear = bookViewModel.Book.PublicationYear;
            Pages = bookViewModel.Book.Pages;
            Price = bookViewModel.Book.Price;
            BookCategory = bookViewModel.Book.BookCategory;
            Language = bookViewModel.Book.Language;
            PublisherId = bookViewModel.Book.PublisherId;
        }

        [Key]
        public int Id { get; set; }

        [Required]
		public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public string CoverURL { get; set; }

        [Required]
        [Display(Name = "Year Published")]
        public int PublicationYear { get; set; }
        [Required]
        public int Pages { get; set; }

        public double Price { get; set; }

        [Display(Name ="Book Category")]
		public BookCategory BookCategory { get; set; }

        public Language Language { get; set; }

        //Relationships
        public List<Author_Book> Author_Book { get; set; }

		public int PublisherId { get; set; }
		[ForeignKey("PublisherId")]
		public Publisher Publisher { get; set; }

    }
}

OnceUpoonABook/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnceUpoonABook.Data;
using OnceUpoonABook.Data.Services.Authors;
using OnceUpoonABook.Data.Services.Books;
using OnceUpoonABook.Data.ViewModels;
using OnceUpoonABook.Models;

namespace OnceUpoonABook.Controllers
{
    [Authorize]
    public class AuthorsController : Controller
    {
        private readonly IAuthorService authorService;
        private readonly IBookService bookService;

        public AuthorsController(IAuthorService authorService, IBookService bookService)
        {
            this.authorService = authorService;
            this.bookService = bookService;
        }
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
            var allAuthors = authorService.GetAll().OrderBy(author => author.AuthorName);
            return View(allAuthors);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Add([Bind("AuthorProfilePicURL,AuthorDescription,AuthorName")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);

            }

            authorService.Add(author);
            return RedirectToAction(nameof(Index));


        }

        [Authorize(Roles = "Admin,Member")]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = authorService.GetById(id);
            if (authorDetails == null) return View("Error");

            var displayAuthor = new AuthorDetailsViewModel(authorDetails);
            displayAuthor.Books = bookService.GetBooksByAuthorId(id).ToList();

            return View(displayAuthor);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var authorDetails = authorService.GetById(id);
            if (authorDetails == null) return View("Error");
            return View(authorDetails);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);

            }

            authorService.Update(id, author);
            return RedirectToAction(nameof(Index));


        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var authorDetails = authorService.GetById(id);
            if (authorDetails == null) return View("Error");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmation(int id)
        {
            var authorDetails =  authorService.GetById(id);
            if (authorDetails == null) return View("Error");

            authorService.DeleteAuthor(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

OnceUpoonABook/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnceUpoonABook.Data;
using OnceUpoonABook.Data.Services.Authors;
using OnceUpoonABook.Data.Services.Books;
using OnceUpoonABook.Data.Services.Publishers;
using OnceUpoonABook.Data.ViewModels;

namespace OnceUpoonABook.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly IBookService bookService;
        private readonly IAuthorService authorService;
        private readonly IPublisherService publisherService;
        public BooksController(IBookService bookService,
            IPublisherService publisherService,
            IAuthorService authorService)
        {
            this.bookService = bookService;
            this.publisherService = publisherService;
            this.authorService = authorService;
        }

        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
            var allBooks = bookService.GetAllBooks();
            return View(allBooks);
        }
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Details(int id)
        {
            var book = bookService.GetBookById(id);
            return View(book);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            var publishers = publisherService.GetAll().OrderBy(publisher => publisher.Name);
            var authors = authorService.GetAll().OrderBy(author => author.AuthorName);

            ViewBag.Authors = authors;
            ViewBag.Publishers = publishers;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Add(AddBookViewModel addBookViewModel)
        {

            if(addBookViewModel.newAuthor != null && !String.IsNullOrWhiteSpace(addBookViewModel.newAuthor.AuthorName)) {

                if (!ModelState.IsValid)
                {
                    var author = authorService.Add(addBookViewModel.newAuthor);
                    addBookViewModel.AuthorIds.Add(author.Id);
                }

            }
            if (!ModelState.IsValid)
            {
                bookService.Add(addBookViewModel);
            }

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var publishers = publisherService.GetAll().OrderBy(publisher => publisher.Name);
            var authors = authorService.GetAll().OrderBy(author => author.AuthorName);

            ViewBag.Authors = authors;
            ViewBag.Publishers = publishers;

            var book = bookService.GetBookById(id);
            EditBookViewModel editBookViewModel = new EditBookViewModel();
            editBookViewModel.Book = book;  
            return View(editBookViewModel);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id, EditBookViewModel bookViewModel)
        {
            bookViewModel.Book.Id = id;
            bookService.UpdateBook(bookViewModel);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {

            var bookdetails = bookService.GetBookById(id);
            if (bookdetails == null) return View("Error");

            var publishers = publisherService.GetAll().OrderBy(publisher => publisher.Name);
            var authors = authorService.GetAll().OrderBy(author => author.AuthorName);

            ViewBag.Authors = authors;
            ViewBag.Publishers = publishers;
            EditBookViewModel editBookViewModel = new EditBookViewModel();
            editBookViewModel.Book = bookdetails;
            return View(editBookViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmation(int id)
        {
            var bookdetails = bookService.GetBookById(id);
            if (bookdetails == null) return View("Error");

            bookService.DeleteBook(id);
            return RedirectToAction(nameof(Index));
        }
    }

}

OnceUpoonABook/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnceUpoonABook.Data.Services.Books;
using OnceUpoonABook.Data.Services.Orders;
using OnceUpoonABook.Data.Services.Orders.ShoppingCart;
using OnceUpoonABook.Data.ViewModels;
using OnceUpoonABook.Models;
using System.Security.Claims;

namespace OnceUpoonABook.Controllers
{
    [Authorize(Roles = "Member")]
    public class OrdersController : Controller
    {
        private readonly IBookService bookService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IOrdersService orderService;

        public OrdersController(IBookService bookService, IShoppingCartService shoppingCartService, IOrdersService orderService)
        {
            this.bookService = bookService;
            this.shoppingCartService = shoppingCartService;
            this.orderService = orderService;
        }


        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orders = orderService.GetOrdersByUserId(userId);

            ViewBag.UserId = userId;

            return View(orders);
        }
        public IActionResult ShoppingCart()
        {

            var shoppingCartVM = new ShoppingCartViewModel();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            shoppingCartVM.CartItems = shoppingCartService.GetItems(userId);
            shoppingCartVM.Total = shoppingCartService.GetTotal(userId);


            return View(shoppingCartVM);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {

            var book = bookService.GetBookById(id);
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (book != null)
            {
                shoppingCartService.AddItemToCart(book, userId);   
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {

            var book = bookService.GetBookById(id);
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (book != null)
            {
                shoppingCartService.RemoveItemFromCart(book, userId);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public IActionResult Checkout()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            orderService.Add(shoppingCartService.GetItems(userId), userId);
            shoppingCartService.Clear(userId);
            return View("Checkout");
        }
    }
}

OnceUpoonABook/Controllers/PublishersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnceUpoonABook.Data;
using OnceUpoonABook.Data.Services.Publishers;
using OnceUpoonABook.Models;

namespace OnceUpoonABook.Controllers
{
    [Authorize]
    public class PublishersController : Controller
	{

        private readonly IPublisherService publisherService;

		public PublishersController(IPublisherService publisherService)
		{
			this.publisherService = publisherService;
		}
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
            var allPublishers = publisherService.GetAll().OrderBy(publisher => publisher.Name);
            return View(allPublishers);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public async Task<IActionResult> Add([Bind("Name,YearCreated,LogoURL")] Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);

            }

            publisherService.Add(publisher);
            return RedirectToAction(nameof(Index));


        }
        [Authorize(Roles = "Admin,Member")]
        public async Task<IActionResult> Details(int id)
        {
            var publisherDetails = publisherService.GetById(id);
            if (publisherDetails == null) return View("Error");
            return View(publisherDetails);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var publisherDetails = publisherService.GetById(id);
            if (publisherDetails == null) return View("Error");
            return View(publisherDetails);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);

            }

            publisherService.Update(id, publisher);
            return RedirectToAction(nameof(Index));


        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var publisher = publisherService.GetById(id);
            if (publisher == null) return View("Error");
            return View(publisher);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmation(int id)
        {
            var publisher = publisherService.GetById(id);
            if (publisher == null) return View("Error");

            publisherService.DeletePublisher(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnceUpoonABook/Views/Books/Add.cshtml
@using OnceUpoonABook.Data.Enums;
@using OnceUpoonABook.Data.ViewModels;
@model AddBookViewModel

@{
    ViewData["Title"] = "Add A Book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Add a new book</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Add">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublicationYear" class="control-label"></label>
                                <input asp-for="PublicationYear" type="number" class="form-control" />
                                <span asp-validation-for="PublicationYear" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Pages" class="control-label"></label>
                                <input asp-for="Pages" type="number" class="form-control" />
                                <span asp-validation-for="Pages" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CoverURL" class="control-label"></label>
                                <input asp-for="CoverURL" class="form-control" />
                                <span asp-validation-for="CoverURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control">
                                    @foreach (var item in ViewBag.Publishers)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                </select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-label"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Language" class="control-label"></label>
                                <select asp-for="Language" class="form-control" asp-items="Html.GetEnumSelectList<Language>()"></select>
                                <span asp-validation-for="Language" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control" multiple>
                                    @foreach (var item in ViewBag.Authors)
                                    {
                                        <option value="@item.Id">@item.AuthorName</option>
                                    }
                                </select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col-12 offset-2">
                   
                                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                        <div class="form-group text-center">
                                            <img id="AuthorImage" class="border-info rounded-circle" style="max-width: 150px" />
                                        </div>
                                        <div class="form-group">
                                        <label asp-for="newAuthor.AuthorProfilePicURL" class="control-label"></label>
                                        <input asp-for="newAuthor.AuthorProfilePicURL" class="form-control" />
                                        <span asp-validation-for="newAuthor.AuthorProfilePicURL" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="newAuthor.AuthorName" class="control-label"></label>
                                            <input asp-for="newAuthor.AuthorName" class="form-control" />
                                            <span asp-validation-for="newAuthor.AuthorName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="newAuthor.AuthorDescription" class="control-label"></label>
                                        <input asp-for="newAuthor.AuthorDescription" class="form-control" />
                                        <span asp-validation-for="newAuthor.AuthorDescription" class="text-danger"></span>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="CoverURL" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-outline-success float-right" />
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#CoverURL").on("change", function () {
            var output = document.getElementById("CoverURL");
            output.src = $(this).val();
        })
        $(document).ready(function () {
            var output = document.getElementById('AuthorImage');
            output.src = $("#newAuthor.AuthorProfilePicURL").val();
        })
        $("#newAuthor.AuthorProfilePicURL").on("change", function () {
            var output = document.getElementById('AuthorImage');
            output.src = $(this).val();
        })
    </script>
}

OnceUpoonABook/Views/Books/Details.cshtml
@model Book

@{
    ViewData["Title"] = "Book Details";
}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">@Model.Title</h3>
            <h6 class="card-subtitle mb-4">
                By
                @if (@Model.Author_Book.Count() < 2)
                {
                    <a asp-controller="Authors" asp-action="Details" asp-route-id="@Model.Author_Book.FirstOrDefault().Author.Id">@Model.Author_Book.FirstOrDefault().Author.AuthorName</a>
                }
                else
                {

                    @foreach (var au in @Model.Author_Book)
                    {
                        <span>
                            <a asp-controller="Authors" asp-action="Details" asp-route-id="@au.Author.Id">@au.Author.AuthorName</a>
                        </span>
                    }
                }

            </h6>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center">
                        <img src="@Model.CoverURL" alt="@Model.Title" class="img-fluid">
                    </div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">Information</h4>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
                    {
                        <div>
                        <small class="text-muted">
                            <a class="btn btn-success text-white float-end"
                           asp-controller="Orders"
                           asp-action="AddToShoppingCart"
                           asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> @Model.Price £
                            </a>
                        </small>
                        </div>
                    }
                    <div>
                        <h5 class="box-title mt-5">Description:</h5>
                    <p>
                        @Model.Description
                    </p>
                   </div>
                    <ul class="list-unstyled">
                        <li>Publisher: <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.Publisher.Id">@Model.Publisher.Name</a></li>
                        <li>Category: <span class="badge badge-pill badge-light-purple">@Model.BookCategory.ToString()</span></li>
                        <li>Language: <span class="badge badge-pill badge-light-purple">@Model.Language.ToString()</span></li>
                        <li>Pages: @Model.Pages</li>
                        <li>Year Published: @Model.PublicationYear</li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li><a class="btn btn-outline-primary" asp-controller="Books" asp-action="Edit" asp-route-id="@Model.Id"><i class="bi bi-pencil-square"></i>Edit </a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

OnceUpoonABook/Views/Books/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "List of all Books";
}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Once Upon A book</h1>
    </div>
</section>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="row mb-3 mt-2">
        <div class="col-md-2 offset-md-10 col-sm-12 x">
            <a class="btn btn-outline-primary float-right" asp-action="Add"><i class="bi bi-plus"></i>Add A Book</a>
        </div>
    </div>
}
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="@item.CoverURL" class="w-100 card-img-top" height="600px" alt="@item.Title">
                <div class="card-body">
                    <p class="card-title">@item.Title</p>
                    <p class="card-text">
                    <p class="card-text"><b class="text-dark-purple">Publisher: </b><a asp-controller="Publishers" asp-action="Details" asp-route-id="@item.Publisher.Id">@item.Publisher.Name</a></p>
                    <p class="card-text"><b class="text-dark-purple">Category: </b><span class="badge badge-pill badge-light-purple">@item.BookCategory.ToString()</span></p>
                    <p class="card-text"><b class="text-dark-purple">Language: </b><span class="badge badge-pill badge-light-purple">@item.Language.ToString()</span></p>
                    <p class="card-text">

                            @if (@item.Author_Book.Count() < 2)
                            {
                            <b>Author: </b> @item.Author_Book.FirstOrDefault().Author.AuthorName
                            }
                            else
                            {
                            <b>Authors: </b>
                                @foreach (var au in @item.Author_Book)
                                {
                                <span>
                                        @au.Author.AuthorName
                                </span>
                                }
                            }

                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-sm btn-outline-secondary" asp-action="Details" asp-route-id="@item.Id">
                                <i class="bi bi-eye"></i> View
                            </a>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                <a class="btn btn-sm btn-outline-secondary" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="bi bi-pen"></i>Edit
                                </a>
                                <a class="btn btn-sm btn-outline-secondary" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="bi bi-trash"></i>Delete
                                </a>
                                }

                        </div>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
                            {
                            <small class="text-muted">
                                <a class="btn btn-success text-white float-end"
                           asp-controller="Orders"
                           asp-action="AddToShoppingCart"
                           asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> @item.Price £
                                </a>
                            </small>
                            }
                    </div>
                </div>
            </div>
        </div>
    }
</div>